export const races = [
  {
    name: 'Bahrain GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Saudi Arabian GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Australian GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Japanese GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Chinese GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Miami GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Emilia Romagna GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Monaco GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Canadian GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Spanish GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Austrian GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'British GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Hungarian GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Belgian GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Dutch GP',
    winner: 'Max Verstappen',
    image: '',
    isCompleted: true,
  },
  {
    name: 'Italian GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Azerbaijan GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Singapore GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'United States GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Mexican GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Brazilian GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Las Vegas GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Qatar GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
  {
    name: 'Abu Dhabi GP',
    winner: '',
    image: '',
    isCompleted: false,
  },
];
