import type { Metadata } from 'next';
import { Bungee } from 'next/font/google';
import { Inter } from 'next/font/google';
import { Montserrat } from 'next/font/google';
import './globals.css';

const bungee = Bungee({
  weight: '400',
  variable: '--font-bungee',
  subsets: ['latin'],
});
const inter = Inter({ variable: '--font-inter', subsets: ['latin'] });
const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${bungee.variable} ${inter.variable} ${montserrat.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
